### ISSUE TITLE
Sample implementation

### ISSUE THREAD

**Issue by Utzel-Butzel** [general-galactic/capacitor-esp-idf-provisioning#2]
Hi @jkennedy1980 Thanks a lot for your effort in providing a Wifi config solution for Capacitor! I just started doing any native development and was wondering if you also have a sample implementation available? Many thanks in advance!

**Comment by jkennedy1980** [comment]
No, I haven't created an example app. I've implemented this in my unreleased production app. Unfortunately, I'm unable to share that code at this time.

Mostly, the api methods are named similarly to the ESP-IDF methods. At an absolute minimum you'd call: `searchESPDevices`, `connect`, `scanWifiList`, `provision`, and `disconnect` in that order. I do implement a few other functions from the ESP-IDF for people who need additional features.

Most of the code ends up being around BLE permissions and exception handling. If I have time I'll try to create an example. Thanks for your interest.

**Comment by Utzel-Butzel** [comment]
@jkennedy1980 Thank you for your response! I'll try figuring it out and if successful provide an example.

**Comment by cobusmeyertopic** [comment]
Hi there @Utzel-Butzel and @jkennedy1980 

Apologies for hijacking your post, but I was wondering if you had any success implementing this package? I'm having issues right off the bat with installation. Trying `npm install @general-galactic/capacitor-esp-idf-provisioning`  gives me `Not Found - GET https://registry.npmjs.org/@general-galactic%2fcapacitor-esp-idf-provisioning - Not found` as it is not found in the registry. Given that the package is not available on the public npm registry, how did you go about installing it? I tried installing it directly from github as npm suggests with `npm install general-galactic/capacitor-esp-idf-provisioning`, but after running `npx cap sync` when I try to implement it I just get `Cannot find module '@general-galactic/capacitor-esp-idf-provisioning' or its corresponding type declarations`.

Could one of you maybe help me to get started with this, I would really appreciate it. 
TIA

**Comment by jkennedy1980** [comment]
This package is not deployed to NPM - it's deployed using Github Packages. You'll need to provide a way for your local NPM to know to look in Github for this package. You can read the official documentation for doing this [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-a-package).

The gist is that you need to add `@general-galactic:registry=https://npm.pkg.github.com` to your `.npmrc` so that NPM knows that packages prefixed with `@general-galactic` are in the Github package registry. I can also work on pushing this package to both registries.

**Comment by cobusmeyertopic** [comment]
Thanks for your response @jkennedy1980. I managed to get it to work eventually. Just needed to start again from the beginning and follow the steps. Thanks for your effort with the package! will be in touch if I have any questions 👍 

PS. Might be helpful for starters to add those steps to the readme.

**Comment by franriibeiro** [comment]
Hi @Utzel-Butzel, @jkennedy1980 and @Utzel-Butzel.

Also sorry for hijacking your post. I am trying to integrate this capacitor-esp-idf-provisioning plugin into my angular capacitor app. I am having some troubles. My goal would be to scan available wifi networks so that the user could select the desired `softAP `coming from the ESP32 device and then provision the device but this seems impossible, right? I do need to connect to the ESP32 device via ble and then provision it with the Wifi credentials, correct?

Following this logic, another question I am having is about the `searchESPDevices` method. It is demanded to include the `devicePrefix`, but this devicePrefix should be what? The ble id that the ESP32 is emitting? This way I would search the ESP device, if the device exists connect to it and then provision it? Am i correct?

Hope i'm not being too confusing and you can help me. If you have some example app or script would be awesome. Many thanks in advance!

**Comment by jkennedy1980** [comment]
@franriibeiro This project only supports the BLE version of esp idf provisioning. I built this for my current project and we only use the BLE setup. Sorry :( If you want to add the softap side of things I'd be happy to accept a pull request.

The `devicePrefix` is set in the esp-idf on the firmware side -[ here's how it's set in their example](https://github.com/espressif/esp-idf/blob/f404fe96b17692e3f1de536a3d73a180cdb53b42/examples/provisioning/wifi_prov_mgr/main/app_main.c#L352).

For the BLE setup, esp-idf does not use advertised service UUIDs like most BLE devices. Instead, they do a scan for all nearby BLE devices and then filter the set using the `devicePrefix` and the BLE device name. I highly recommend you change the default device prefix in your firmware. If you don't, your device will show up in the espressif idf setup apps like  [these](https://www.espressif.com/en/support/download/apps).

**Comment by franriibeiro** [comment]
@jkennedy1980 Thank you very much for your response!

**Comment by franriibeiro** [comment]
Hi again @jkennedy1980 , 

I have implemented the plugin and it works but i'm having trouble with bluetooth and location permissions. I have used your 
`EspProvisioning.requestPermissions` and `EspProvisioning.checkPermissions` methods to request and get the resulting permissions and I am getting granted in both of the required permission. However, when i try to search for ESP devices, I'm getting `Error: Bluetooth (Nearby Devices) and Location permissions are required`. 
 
I am using android studio to deploy the app on an Android 9 phone, do you think it could have anything to do with this? I have also tried to request permissions using `{ AndroidPermissions } from '@ionic-native/android-permissions/ngx'` but I always get the same error, even thought I am checking that the permission are granted.
```
const fineLocationPermission = await this.androidPermissions.requestPermission(
        this.androidPermissions.PERMISSION.ACCESS_FINE_LOCATION
      );
      const bluetoothPermission = await this.androidPermissions.requestPermission(
        this.androidPermissions.PERMISSION.BLUETOOTH
      );
      const bluetoothAdminPermission = await this.androidPermissions.requestPermission(
        this.androidPermissions.PERMISSION.BLUETOOTH_ADMIN
      );
```

 I also updated my AndroidManifest.xml to include the necessary permissions. 

   ```
 <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />

```

If you could help I would highly appreciate. Thank you in advance

**Comment by franriibeiro** [comment]
Hello again @jkennedy1980, 

On the latest version of the plugin (0.0.86), what are the limitations with android devices using android sdk < 12 ?

Thank you in advance
